use_frameworks!

target 'SwiftPic_Example' do
  pod 'SwiftPic', :path => '../'

  target 'SwiftPic_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
